# Generated by Django 3.2.19 on 2024-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question1', models.BooleanField()),
                ('question2', models.BooleanField()),
                ('question3', models.BooleanField()),
            ],
        ),
    ]
