# Generated by Django 3.2.19 on 2024-08-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240818_0802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresponse',
            old_name='question1',
            new_name='alteraciones_equilibrio',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question2',
            new_name='alteraciones_visuales',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question3',
            new_name='debilidad_miembros',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question4',
            new_name='dolor_abdominal',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question5',
            new_name='dolor_abdominal_mayor_50',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question6',
            new_name='dolor_torax',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='motivo',
            new_name='motivo_de_consulta',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question7',
            new_name='paralisis_facial',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='question8',
            new_name='sangrado',
        ),
    ]
